// src/components/Forca.vue
<template>
    <div class="forca">
        <img :src="`https://raw.githubusercontent.com/william-costa/wdev-hangman-game-resources/master/images/hangman/${erros}.svg`">
    </div>
</template>
  
<script>
  export default {
    name: 'Forca',
  
    props: {
      erros: {
        type: Number,
        default: 0
      }
    }
  };
</script>
  
<style scoped>
  .forca img {
    height: 200px;
  }

  @media (max-width: 600px) {
    .forca img {
      height: 130px;
    }
  }
</style>

// src/components/Forca/Forca.tsx
import "./Forca.css"

type ForcaProps = {
  erros?: Number;
}

export default function Forca({
  erros = 0
}: ForcaProps) {
    return (
        <div className="forca">
            <img src={`https://raw.githubusercontent.com/william-costa/wdev-hangman-game-resources/master/images/hangman/${erros}.svg`}></img>
        </div>
    )
}
