// src/components/Palavra/Palavra.tsx
import "./Palavra.css"
import { useMemo } from "react";

type PalavraProps = {
  palavra: string,
  etapa: string,
  verificarLetra: (letra: string) => boolean;
}

export default function Palavra({
  palavra,
  etapa,
  verificarLetra
}: PalavraProps) {

    const linhasPalavra = useMemo(() => {
    const limitePorLinha = window.innerWidth < 600 ? 12 : 24;
    const linhas: string[] = [];
    let linhaAtual = "";

    palavra.split("").forEach((letra) => {
      if (linhaAtual.length < limitePorLinha) {
        linhaAtual += letra;
      } else {
        linhas.push(linhaAtual);
        linhaAtual = letra;
      }
    });

    if (linhaAtual) {
      linhas.push(linhaAtual);
    }

    return linhas;
  }, [palavra]);

    return (
        <div className="palavra">
      
            {linhasPalavra.map((linha, index) => (
                <div key={index} className="palavra-letras">
                
                {linha.split("").map((letra, key) => (
                    <div key={key} className="palavra-letra">
                    {
                      letra === " " ? "-" : (verificarLetra(letra) || etapa === "final") ? letra : ""
                    }
                    </div>
                ))}

                </div>
            ))}

        </div>
    )
}

// src/components/Palavra.vue
<template>
  <div class="palavra">
    <div 
      v-for="(linha, index) in linhasPalavra" 
      :key="index" 
      class="palavra-letras"
    >
      <div 
        v-for="(letra, key) in linha" 
        :key="key" 
        class="palavra-letra" 
      >
        {{ (letra === ' ') ? '-' : (verificarLetra(letra) || etapa === 'final') ? letra : '' }}
      </div>
    </div>
    <div v-if="dica" class="palavra-dica">Dica: {{ dica }}</div>
  </div>
</template>

<script>
import { computed } from 'vue';

export default {
  name: 'Palavra',
  
  props: {
    palavra: {
      type: String,
      required: true
    },
    dica: {
      type: String
    },
    etapa: {
      type: String
    },
    verificarLetra: {
      type: Function,
      required: true
    }
  },

  setup(props) {
    const linhasPalavra = computed(() => {
      const limitePorLinha = window.innerWidth < 600 ? 12 : 24;
      const linhas = [];
      let linhaAtual = '';

      props.palavra.split('').forEach((letra) => {
        if (linhaAtual.length < limitePorLinha) {
          linhaAtual += letra;
        } else {
          linhas.push(linhaAtual);
          linhaAtual = letra;
        }
      });

      if (linhaAtual) {
        linhas.push(linhaAtual);
      }

      return linhas;
    });

    return {
      linhasPalavra
    };
  }
};
</script>

<style scoped>
.palavra {
  text-transform: uppercase;
  display: flex;
  flex-direction: column;
  text-align: center;
  align-items: center;
}

.palavra-letras {
  display: flex;
  flex-direction: row;
  margin-bottom: 20px;
  justify-content: center; 
}

.palavra-letra {
  height: 40px;
  width: 40px;
  margin: 0 5px;
  font-size: 23px;
  border-bottom: 1px solid var(--color-text-light);
  display: flex;
  justify-content: center;
  align-items: center;
  text-align: center;
}

@media (max-width: 600px) {
  .palavra-letra {
    width: 20px; 
    font-size: 16px; 
  }
}
</style>
